language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CC" = "gcc" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_script:
  - if [ "$CC" = "gcc" ]; then $CC --version; fi
script: make all
